### ISSUE TITLE
Preparing build and examples for Three.js PR.

### ISSUE THREAD

**Issue by sciecode** [threejs/lwoloader#16]
Given all recent loader changes, I believe it's time to prepare a stable build for three.js PR. @looeee thoughts?

We are changing a few important things on the folder structure, I feel like we should push this change asap.  Before people start using the past hierarchy on their projects. 

There are few things we need before that:

Recent PR #15 introduces Physical materials for models using BSDF, this means some of the texts on a few models are now mistakenly referring the materials as Standard. Including "Materials.lwo" which, in my opinion, should be the new example model on master repo. This would need to be fixed. 

I've also noticed that the `glossiness` attribute isn't quite correctly mapped yet. A test model with  smaller glossiness steps would be required for the correct mapping. ( more spheres haha ) 

@onthez  would it possible for you to make these changes?

**Comment by onthez** [comment]
I totally agree.  I doubt it's seeing substantial use yet, but we should get this version out reasonably quick since it changes some of the basics.

Yes, I can update those models.
When the pull request is submitted to the main repo, can the existing test model and it's textures be pulled down?  There is one image that isn't licensed for public release.  I used it in testing but didn't intend it to go out.

**Comment by sciecode** [comment]
> Yes, I can update those models.

Thank you.

> When the pull request is submitted to the main repo, can the existing test model and it's textures be pulled down? There is one image that isn't licensed for public release. I used it in testing but didn't intend it to go out.

We are just pushing one model to the main repo. Just so we have an example of the loader working properly. The rest of the models are just for testing purposes and they will remain only in this repository. 

I believe the best one would be "Materials.lwo", because it shows how each of the material properties are working properly. Speaking of which, maybe we could also include clearcoat and color highlights on that one, since they will be working as soon as we merge PR #15.

**Comment by looeee** [comment]
> I believe the best one would be "Materials.lwo"

How about materials.lwo but with the rocket in the middle? That would look pretty good. Probably two models is OK since they are pretty small.

![example](https://user-images.githubusercontent.com/5307958/57008264-142d3500-6c19-11e9-81e1-b26fa338d388.png)

**Comment by looeee** [comment]
> Given all recent loader changes, I believe it's time to prepare a stable build for three.js PR.

Agreed. I want to proceed cautiously here though, since this is the first project to be added to this organisation and developed in this way. 

@sciecode can you write up a quick executive summary of the changes since the last version? Just a list of bullet points is fine.

**Comment by sciecode** [comment]
> How about materials.lwo but with the rocket in the middle? That would look pretty good. 

I like the idea of including the rocket model as well.
@onthez  Is everything on model licensed to the public? (non-textured version)

> @sciecode can you write up a quick executive summary of the changes since the last version? Just a list of bullet points is fine.

Absolutely. I'll format it as official Threejs release notes.
Just listing the changes relative to LWOLoader, of course.

- **Global**
    - Fixed content directory. Inline with LightWave default structure. #6 
    - Added `resourcePath` parameter to specify root content directory. #6
- **IFFparser**
    - Separated `LWO2` and `LWO3` parsers into version specific modules. #10
    - Added support for basic surfaces chunks. `specular`, `shininess`, `emissive` and `reflectivity`. #11
    - Added `Debugger` to log model `FORM` and `CHUNK` structure and details skipped chunks. #14 
- **Materials**
   - Updated attributes parsing to conform new surface chunks. #11
   - Added support for `Color Highlight` on phong materials. #15
   - Uses `MeshPhysicalMaterial` when LW material includes Clearcoat. #15

**Comment by onthez** [comment]
> I like the idea of including the rocket model as well.
> @onthez Is everything on that model licensed to the public? (non-textured version)

@sciecode Yes, all assets I've included in this repo (models, textures, environment map) are all okay to use.  You could include the attribution below:
Models by [on the z](https://onthez.com/). Licensed under Creative Commons Attribution 4.0 International License
Environment images by [HDRI Haven](https://hdrihaven.com/). Licensed under Creative Commons CC0 Public Domain
Texture images by [CC0 Textures](https://cc0textures.com).  Licensed under Creative Commons CC0 Public Domain

I just wrapped up the new model Demo.lwo
I'll submit a pull request in a moment.

**Comment by sciecode** [comment]
Oh, I'm sorry Justin. I must've misread the original question regarding removing the unlicensed texture.
Yes, we will remove all textures that are currently being used on master repo and replace with the ones on the new demo.lwo. So, you don't need to worry about that.

I'll make sure to include the respective licenses when pushing to Threejs master repo. Thank you.

**Comment by looeee** [comment]
> Models by on the z. Licensed under Creative Commons Attribution 4.0 International License
Environment images by HDRI Haven. Licensed under Creative Commons CC0 Public Domain
Texture images by CC0 Textures. Licensed under Creative Commons CC0 Public Domain

We'll put " Models by on the z." in the example text, usually the license gets added as license.txt file in the same directory as the models.

**Comment by looeee** [comment]
Great! I think we're good to go! 😁 🚀 

@sciecode do you want to make the PR? We should bump the version to 1.1 as well.

**Comment by sciecode** [comment]
Just did it. mrdoob/three.js#16370

**Comment by sciecode** [comment]
![image](https://user-images.githubusercontent.com/3927951/58949532-0f512900-8763-11e9-90a7-8570ce628418.png)
