### ISSUE TITLE
Transparent materials - metalness and opacity

### ISSUE THREAD

**Issue by onthez** [threejs/lwoloader#30]
Near line 667, when attributes.transparent && attributes.opacity < 0.999
Currently the behavior is to use the transparency from the Lightwave material as the opacity.
If refraction does not equal 1, then attributes.opacity should be set to 1.
opacity fades out the refraction. 1 is almost always a closer visual result to the material settings from Lightwave in these cases.

Also just a few lines down, near 679, when attributes.metalness !== undefined
Currently the behavior is to delete the metalness attribute.

A better handling of this case is to set
attributes.metalness = 1;

Thanks so much!
I just happen to get the pull request notification from #24 and thought I might pass a few of these as well.

**Comment by looeee** [comment]
Tracking upstream in https://github.com/mrdoob/three.js/issues/19383
